config/routes.rb
Rails.application.routes.draw do
  resources :relationships
  resources :rants
  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'

  resources :after_signup
  resources :users

    root 'rants#index'

    get 'friends', to: 'users#friends', as:'friends'

end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/rant.rb
class Rant < ActiveRecord::Base
  belongs_to :user
  validates :content, length: {maximum: 170}
  acts_as_followable

  def self.timeline(user)
    following_ids = user.all_following.map(&:id)
    all_ids= following_ids << user.id
    Rant.where(user_id: all_ids).order("created_at DESC")
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rants
  acts_as_authentic do |c|
    c.login_field = :username
  end
  has_many :follower_relationships, class_name: "Relationship", foreign_key:"followed_id"
  has_many :followed_relationships, class_name: "Relationship", foreign_key:"follower_id"
  has_many :followers, through: :follower_relationships
  has_many :followeds, through: :followed_relationships

  def following? user
    self.followeds.include? user
  end

  def follow user
    Relationship.create follower_id: self.id, followed_id: user.id
  end

  def relate(user)
    Relationship.where(follower_id: self.id,
    followed_id: user.id).first_or_initialize
  end

  def all_following
    followeds
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/after_signup_controller.rb
class AfterSignupController < ApplicationController
  include Wicked::Wizard

  steps :confirm_password, :confirm_profile, :find_friends

  def show
      @user = current_user
      case step
      when :find_friends
        @friends = @user.find_friends
      end
      render_wizard
    end

    def update
      @user = current_user
      case step
      when :confirm_password
        @user.update_attributes(params[:user])
      end
      render_wizard @user
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user_session, :current_user
  before_action :current_user

private

def current_user
  return @current_user if defined?(@current_user)
  @current_user = current_user_session && current_user_session.user
end

def current_user_session
  if defined?(@current_user_session)
    return @current_user_session
  else
    @current_user_session = UserSession.find
  end
end

def require_user
  unless @current_user
    flash[:alert]="You have to be logged in"
    redirect_to root_url
  end
end

def require_no_user
  if @current_user
      flash[:alert]="You are already logged in"
      redirect_to root_url
  end
end

end

app/controllers/rants_controller.rb
class RantsController < ApplicationController
  before_action :set_rant, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:new,:create, :update, :destroy]

  def index
    if current_user
    @rants = Rant.timeline(current_user).order("created_at DESC").page(params[:page] || 1).per(10)
    else
    @rants= Rant.all.order("created_at DESC").page(params[:page] || 1).per(10)
    end
    @rant = Rant.new
    @users=User.all

  end

  def show
    @rant.content
  end

  def new
    @rant=Rant.new
  end

  def create
    @rant = Rant.new(rant_params)
    @rant.user= current_user
    if @rant.save
        redirect_to users_path
    else
      flash[:alert]= "There has been a problem saving your rant! Sorry."
      render :new
    end
  end

  def update
    if @rant.update(rant_params)
      redirect_to users_path, [:alert] => 'Rant was successfully update.'
    else
      render :edit
    end
  end

  def destroy
    @rant.destroy
      redirect_to rants_path [:alert] => 'Rant was successfully deleted.'
  end

  private

  def set_rant
    @rant = Rant.find(params[:id])
    unless @rant.user == @current_user
      flash[:alert]= "You are not the creator of this rant!"
      redirect_to root_url
    end
  end

  def rant_params
    params.require(:rant).permit(:content, :user_id)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
       @relationship = Relationship.new
       @relationship.followed_id = params[:followed_id]
       @relationship.follower_id = current_user.id

   if @relationship.save
       redirect_to User.find params[:followed_id]
   else
       flash[:error] = "Couldn't Follow"
       redirect_to root_url
   end
 end

 def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    redirect_to user_path params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_no_user, only: [:new, :create]
  before_action :require_user, only: [:destroy]

  def new
    @session = UserSession.new
  end

  def create
    @session = UserSession.new(session_params)
    if @session.save
      redirect_to rants_path, notice: "You're logged in. Rant away!"
    else
      flash[:error] = "Wrong Username or Password."
      redirect_to rants_path
    end
  end

  def destroy
    session[:user_id] = nil
    current_user_session.destroy
    redirect_to rants_path, notice: "You've logged out. (And hopefully cooled off a bit)"
  end

  private

  def session_params
    params.require(:session).permit( :username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:destroy]
  before_action :require_no_user, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @user=current_user
    @users = User.all
    @rants = Rant.all.order("created_at DESC").page(params[:page] || 1).per(10)
    @rant = Rant.new
    @relationship = Relationship.where(follower_id: current_user.id,
    followed_id: @user.id).first_or_initialize if current_user
  end

  def new
    if current_user
      redirect_to user_path
    else
      @user =User.new
    end
  end

  def update
    @rant = Rant.new
    @rant.save
    redirect_to users_path, method: :post
  end


  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thank you for signing up!"
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated!'
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @users= User.all
    @rant = Rant.new
    @rants = @user.rants.order("created_at DESC").page(params[:page] || 1).per(10)
    @relationship = Relationship.where(follower_id: current_user.id,
    followed_id: @user.id).first_or_initialize if current_user
  end

  def destroy
    @user.destroy
      redirect_to root_path
  end

  def friends
    @user = current_user
    @rant= Rant.new
    @rants = Rant.all.order("created_at DESC").page(params[:page] || 1).per(10)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:username, :email, :password, :name, :password_confirmation, :content)
  end

end

app/helpers/after_signup_helper.rb
module AfterSignupHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rants_helper.rb
module RantsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/after_signup/confirm_password.html.erb
<%= link_to 'skip', next_wizard_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeamTranslationTwitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <body>
      <header>
        <div class = "container-fluid">
          <div class = "jumbotron">
          <p id= "title"> RAGE RANT</p>
          <div class = "row col-xs-12">
            <% if @current_user%>
              <h5>Welcome, <%=link_to @current_user.name, user_path(@current_user)%> !</h5>
              <%= link_to "Home", root_url, :class => "btn btn-medium btn-primary" %>
              <%= link_to "Log out",  sessions_destroy_path(@current_user),method: :delete, :class => "btn btn-medium btn-primary" %>
            <%else%>
              <%= form_tag sessions_create_path do %>
                <%= text_field_tag "session[username]", nil, placeholder: "username" %>
                <%= password_field_tag "session[password]", nil,  placeholder: "password" %>
                <%= submit_tag "Log In"%>
                <%end%>
                <%= link_to "Sign Up for an Account", new_user_path, :class => "btn btn-medium btn-primary" %>
            <%end%>
          </div>
        </div>
      </div>
      </header>
      <div>
          <div class= "posts">
              <% flash.each do |name, msg| %>
                  <%= content_tag :div, msg, class: "flash #{name}" %>
              <% end %>
              <%= yield %>
          </div>
      </div>
      <footer>
        <br>
          <div>
              Rage Rant - Tell us how you really feel!
          </div>
      </footer>
  </body>
  </html>

app/views/rants/index.html.erb
<h1 id= "header">Rants </h1>
<% if current_user %>
  <div class="panel_left">
    <h3>Rant your Rage</h3>
      <%= bootstrap_form_for @rant do |f|%>
    <div class="control-group">
      <%= f.text_area :content, skip_label:true, :size => "100x5", :placeholder => "Rant away..." %>
      <%= f.submit "Rant!", method: :post %>
    </div>
      <% end %>
  </div>
<% end %>
<% @rants.each do |rant| %>
  <br><br><p><a href="<%= user_path rant.user %>"><%= rant.user.name %></a>
  @<%= rant.user.username %></p>
  <p><%= rant.content %></p>
  <span>Posted <%= time_ago_in_words(rant.created_at) %> ago</span>
  <span><%= rant.user.followers.count %>   Followers</span>
  <span><%= rant.user.followeds.count %>   Following</span>
  <br>
  <br>
  <% if current_user && rant.user != current_user %>
    <% if current_user.following? rant.user %>
      <%= form_tag relationship_path(current_user.relate(rant.user)), method: :delete do %>
        <%= submit_tag "Unfollow" %>
        <% end %>
    <% else %>
      <%= form_for current_user.relate(rant.user) do %>
        <%= hidden_field_tag :followed_id, rant.user.id %>
        <%= submit_tag "Follow" %>
        <% end %>
    <% end %>
  <% end %>
<% end %>
<br>

<%= paginate @rants %>

app/views/rants/new.html.erb
<p>
<%= bootstrap_form_for @rant do |f|%>
  <%= f.text_area :content, skip_label:true, :size => "100x5"%>
  <%= f.submit "Rant!" %>
<% end %>
</p>

app/views/users/friends.html.erb
<% if current_user %>
<div>
    <h1>Rant your Rage</h1>
    <p>
    <%= bootstrap_form_for @rant do |f| %>
        <%= f.text_area :content, skip_label:true, :size => "100x5"%>
        <%= f.submit "Rant!" %>
    <% end %>
    </p>
</div>
<% end %>
<div class="panel left">
    <h1>Friends' Rants</h1>
    <% @rants.each do |r| %>
        <div>
            <p><a href="<%= user_path r.user %>"><%= r.user.name %></a>
            @<%= r.user.username %> Posted <%= time_ago_in_words(r.created_at) %></p>
            <p> <%= r.content %> </p>
            <p><%= r.user.followers.count %> Followers
            <%= r.user.followeds.count %> Following</p><br>
            <% if current_user && r.user != current_user %>
              <% if current_user.following? r.user %>
                <%= form_tag relationship_path, method: :delete do %>
                  <%= submit_tag "Unfollow" %>
                  <% end %>
              <% else %>
                <%= bootstrap_form_for @relationship do %>
                  <%= hidden_field_tag :followed_id, r.user.id %>
                  <%= submit_tag "Follow" %>
                  <% end %>
              <% end %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/users/index.html.erb
<% if current_user %>
  <div class="panel left">
    <h1>Rant your Rage</h1>
      <%= bootstrap_form_for @rant do |f|%>
    <div class="control-group">
      <%= f.text_area :content, skip_label:true, :size => "100x5", :placeholder => "Rant away..." %>
      <%= f.submit "Rant!", method: :post %>
    </div>
      <% end %>
  </div>
<% end %>
<div>
  <%= link_to "Public Rants", rants_path %>
  <%= link_to "My Profile", current_user %>
</div>
<div class = "row">
  <div class="panel_left col-xs-12 col-md-8">
    <br>
    <h4>Recent Rants</h4>
    <% @rants.each do |rant| %>
      <br>
      <p><a href="<%= user_path rant.user %>"><%= rant.user.name %></a> @ <%=rant.user.username%>   Posted <%= time_ago_in_words(rant.created_at) %> ago</p>
      <p><%= rant.content %></p>
      <p><%= rant.user.followers.count %> Followers  <%= rant.user.followeds.count %> Following</p><br>
        <% if current_user && @user != current_user %>
          <% if current_user.following? @user %>
            <%= form_tag relationship_path(current_user.relate(@user)), method: :delete do %>
              <%= submit_tag "Unfollow" %>
              <% end %>
            <% else %>
            <%= form_for @relationship do %>
              <%= hidden_field_tag :followed_id, @user.id %>
              <%= submit_tag "Follow" %>
              <% end %>
            <% end %>
        <% end %>
      <% end %>
      <br>
  </div>

    <div class = "panel_right col-xs-12 col-md-4">
      <h4>Profile Info</h4>
      <p><%= current_user.rants.size %> Rants</p>
      <p><%= current_user.followers.count %> Followers</p>
      <p><%= current_user.followeds.count %> Following</p><br>
    </div>
</div>

<%= paginate @rants %>

app/views/users/new.html.erb
<div class="panel right">
  <h1>New to Rage Rant?</h1>

  <%= bootstrap_form_for @user do |f| %>
    <% if @user.errors.any? %>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>


    <%= f.text_field :name, placeholder: "Your Name" %>
    <%= f.text_field :email, placeholder: "Email" %>
    <%= f.text_field :username, placeholder: "Username" %>
    <%= f.password_field :password, placeholder: "Password" %>
    <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
    <br>
    <%= f.submit "Create Account" %>
  <% end %>
<br>
</div>

app/views/users/show.html.erb
<% if current_user %>
  <div class="panel right">
    <h1>Rant your Rage</h1>
    <p>
    <%= bootstrap_form_for @rant do |f|%>
      <%= f.text_area :content,skip_label:true, :size=> "100x5", :placeholder => "Rant away..."%><br>
      <%= f.submit "Rant!" %>
      <% end %>
    </p>
  </div>
<% end %>

<h1><%=@user.name%>'s Rage Page</h1>
<div class="row">
  <div class="panel_left col-xs-12 col-md-8">
    <br>
    <h4>Your Rants</h4>
    <% @rants.each do |rant| %>
      <br>
      <p><a href="<%= user_path rant.user %>"><%= rant.user.name %></a> @ <%=rant.user.username%>   Posted <%= time_ago_in_words(rant.created_at) %> ago</p>
      <p><%= rant.content %></p>
      <p><%= rant.user.follower_relationships.count %> Followers  <%= rant.user.followed_relationships.count %> Following</p><br>
        <% if current_user && @user != current_user %>
          <% if current_user.following? @user %>
            <%= form_tag relationship_path(current_user.relate(@user)), method: :delete do %>
              <%= submit_tag "Unfollow" %>
              <% end %>
            <% else %>
            <%= form_for @relationship do %>
              <%= hidden_field_tag :followed_id, @user.id %>
              <%= submit_tag "Follow" %>
              <% end %>
            <% end %>
        <% end %>
      <% end %>
      <br>
  </div>
  <div class="panel_right col-xs-12 col-md-4">
    <h3>Profile Info</h3>
      <p><%=@user.name %> has made <%= @user.rants.size %> rants</p>
      <p><%= @user.followers.count %> Followers <%= @user.followeds.count %> Following</p>
        <% if @user.rants.any? %>
          <p><%= @user.name %>'s first rant: <%= @user.rants.first.content %></p>
          <%else%>
        <%end%>
      <br>
      <br>
    <h3>Followers </h3>
  <% @user.followers.each do |u|%>
      <p><%=link_to u.name, user_path(u) %></p>
      <% end %>
    <h3>Following</h3>
  <% @user.followeds.each do |u|%>
    <p> <%= link_to u.name, user_path(u) %></p>
    <% end %>
  </div><br>
</div>
<%= paginate @rants %>